# Generated by Django 4.2.2 on 2023-08-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
