# Generated by Django 4.2.2 on 2023-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='ledger_id',
            new_name='module_id',
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(),
        ),
    ]
