# Generated by Django 4.2.2 on 2023-08-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('control_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('asset_description', models.CharField(max_length=100)),
                ('account_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepreciationLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('term', models.IntegerField()),
                ('particulars', models.CharField(max_length=100)),
                ('debit', models.CharField(default=0, max_length=100)),
                ('credit', models.CharField(default=0, max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('depreciation_date', models.CharField(max_length=100)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=100)),
                ('debit', models.CharField(default=0, max_length=100)),
                ('credit', models.CharField(default=0, max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('trans_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_ledger', to='assets.asset')),
            ],
        ),
    ]
