# Generated by Django 4.2.2 on 2023-07-20 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='term',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_ledger', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_ledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
