# Generated by Django 4.2.2 on 2023-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('approval_type', models.CharField(max_length=100)),
                ('module_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=100)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('approved_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
