# Generated by Django 4.2.2 on 2023-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approval_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='account_number',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
