# Generated by Django 4.2.2 on 2023-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approval_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='data',
            new_name='new_data',
        ),
        migrations.AddField(
            model_name='approval',
            name='old_data',
            field=models.JSONField(default='2123'),
            preserve_default=False,
        ),
    ]
