# Generated by Django 4.2.2 on 2023-09-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_rename_data_approval_new_data_approval_old_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approval_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
