# Generated by Django 4.2.2 on 2023-09-10 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvals', '0005_approval_approval_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='approval_submitted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
