# Generated by Django 4.2.2 on 2023-08-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receivables', '0003_rename_registered_name_receivables_funds_registered_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=100)),
                ('debit', models.CharField(default=0, max_length=100)),
                ('credit', models.CharField(default=0, max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('trans_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivables', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables_ledger', to='receivables.receivables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables_ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
