# Generated by Django 4.2.2 on 2023-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payables',
            name='account_type',
            field=models.IntegerField(),
        ),
    ]
