# Generated by Django 4.2.2 on 2023-08-13 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payables',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledger',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_ledger', to='payables.payables'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='payables.payables'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
