# Generated by Django 4.2.2 on 2023-08-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0002_alter_payables_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='payables.payables'),
        ),
    ]
