# Generated by Django 4.2.2 on 2023-08-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0004_alter_contacts_payables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to='payables.payables'),
        ),
    ]
