# Generated by Django 4.2.2 on 2023-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0005_alter_contacts_payables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='personnel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
