# Generated by Django 4.2.2 on 2023-08-02 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payables', '0006_alter_contacts_contact_no_alter_contacts_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to='payables.payables'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
