# Generated by Django 4.2.2 on 2023-08-02 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payables', '0007_alter_contacts_payables_alter_contacts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to='payables.payables'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='personnel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
