# Generated by Django 4.2.2 on 2023-08-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0008_alter_contacts_contact_no_alter_contacts_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='payables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='payables.payables'),
        ),
    ]
