# Generated by Django 4.2.2 on 2023-08-04 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0009_alter_contacts_payables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
