# Generated by Django 4.2.2 on 2023-08-04 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0011_alter_ledger_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 20, 23, 51, 704359, tzinfo=datetime.timezone.utc)),
        ),
    ]
