# Generated by Django 4.2.2 on 2023-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0012_alter_ledger_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
