# Generated by Django 4.2.2 on 2023-08-04 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0013_alter_ledger_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
