# Generated by Django 4.2.2 on 2023-08-13 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners_equity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersequity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_equity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledger',
            name='owners_equity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_equity_ledger', to='owners_equity.ownersequity'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_equity_ledger', to=settings.AUTH_USER_MODEL),
        ),
    ]
