# Generated by Django 4.2.2 on 2023-07-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_equity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersequity',
            name='account_status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
