# Generated by Django 4.2.2 on 2023-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners_equity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersequity',
            name='under_approval',
            field=models.BooleanField(default=True),
        ),
    ]
