# Generated by Django 4.2.2 on 2023-07-20 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners_equity', '0003_alter_ownersequity_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersequity',
            name='account_status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=100)),
                ('debit', models.CharField(default=0, max_length=100)),
                ('credit', models.CharField(default=0, max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('trans_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_equity_ledger', to='owners_equity.ownersequity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners_equity_ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
