# Generated by Django 4.2.2 on 2023-07-20 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners_equity', '0004_alter_ownersequity_account_status_ledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='asset',
            new_name='owners_equity_id',
        ),
    ]
