# Generated by Django 4.2.2 on 2023-07-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners_equity', '0005_rename_asset_ledger_owners_equity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='owners_equity_id',
            new_name='owners_equity',
        ),
    ]
