# Generated by Django 4.2.2 on 2023-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='No address', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
