# Generated by Django 4.2.2 on 2023-08-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
