# Generated by Django 4.2.2 on 2023-09-07 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0004_alter_company_address_alter_supplier_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="barangay",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barangay",
                to="components.municipality",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="barangay",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="barangay",
                to="components.province",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="municipality",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipality",
                to="components.province",
            ),
            preserve_default=False,
        ),
    ]
