# Generated by Django 4.2.2 on 2023-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ledger', models.CharField(max_length=100)),
                ('module_id', models.IntegerField()),
                ('code', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
