# Generated by Django 4.2.2 on 2023-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='account_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ownersequity',
            name='account_status',
            field=models.IntegerField(default=1),
        ),
    ]
