# Generated by Django 4.2.2 on 2023-07-04 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_asset_account_status_alter_asset_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=100)),
                ('term', models.IntegerField()),
                ('particulars', models.CharField(max_length=100)),
                ('debit', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('control_number', models.CharField(max_length=100)),
                ('trans_number', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='app.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
