# Generated by Django 4.2.2 on 2023-07-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='owners_equity',
            new_name='bank_account',
        ),
    ]
